server:
  port: 8000
spring:
  application:
    name: spring-security-oauth2
  datasource:
    name: dataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_security
    username: root
    password: root
    druid:
      initial-size: 2
      max-active: 100
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5s
    database: 4
    lettuce:
      pool:
        max-active: 50
        max-idle: 50
        min-idle: 0
        max-wait: 2000ms
logging:
  level:
    org.springframework: DEBUG
